### ISSUE TITLE
getting started help

### ISSUE THREAD

**Issue by fakefarm** [darrencauthon/lemonade_stand#1]
Hey Darren,

I was teaching my 7 year old son how to play lemonade stand today on the xbox. Got me thinking about rewriting the game. I figured I'd do a quick search on Gh to see if anyone else had anything and I found your gem. I spent the last 30m or so reviewing and I'd like to see if / how I can help if you'd be interested. 

I'd also like to practice some of my frontend chops so maybe we can turn this into an interactive game of sorts.

I checked your readme and tried to boot both the game on console but I get

```
./play_ls
/Users/davidwoodall/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- lemonade_stand (LoadError)
    from /Users/davidwoodall/.rbenv/versions/2.1.2/lib/ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from ./play_ls:3:in `<main>'
```

Also, 

what command are you using to run the specs?
`bundle exec rake` isn't working for me for some reason

Thanks!

**Comment by fakefarm** [comment]
Also, I tried running the tests and got;

```
$ bundel exec rake
rake aborted!
Don't know how to build task 'default'

(See full trace by running task with --trace)
```

**Comment by darrencauthon** [comment]
Hmm... I'm not sure, but I'll take a look this weekend!  

I'll get the tests running through CI to verify they work outside of my computer. Then we'll see where to go from there. 

I'll tag you on this ticket when I have some progress.

**Comment by fakefarm** [comment]
Actually, I figured it out last nigh;

I hadn't used rakes `test` method before, but the specs run (and all pass) when I do

`bundle exec rake test`

I'll add it to the `README`  :+1:
